# Generated by Django 4.2.3 on 2025-10-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the organization",
                        max_length=255,
                        unique=True,
                        verbose_name="Organization Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the organization", verbose_name="Description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this organization is active", verbose_name="Is Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.SlugField(
                        help_text="Unique namespace identifier", unique=True, verbose_name="Namespace Name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the namespace", verbose_name="Description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this namespace is active", verbose_name="Is Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this namespace",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this namespace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="shorturl.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "shortcode",
                    models.CharField(help_text="The short code for the URL", max_length=10, verbose_name="Short Code"),
                ),
                (
                    "original_url",
                    models.URLField(
                        help_text="The original URL to be shortened", max_length=2000, verbose_name="Original URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this short URL has been accessed",
                        verbose_name="Click Count",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this short URL expires (optional)",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, help_text="Whether this short URL is private", verbose_name="Is Private"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this short URL is active", verbose_name="Is Active"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional title for the short URL", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for the short URL", verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this short URL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        help_text="Namespace this short URL belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shorturls",
                        to="shorturl.namespace",
                        verbose_name="Namespace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["namespace", "shortcode"], name="shorturl_sh_namespa_b7ad25_idx"),
                    models.Index(fields=["created_at"], name="shorturl_sh_created_d182a8_idx"),
                    models.Index(fields=["is_active"], name="shorturl_sh_is_acti_190890_idx"),
                ],
                "unique_together": {("namespace", "shortcode")},
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("editor", "Editor"), ("viewer", "Viewer")],
                        help_text="Role of the user in the organization",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True, verbose_name="Invited At")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this membership is active", verbose_name="Is Active"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization the user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="shorturl.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-invited_at"],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
