# Generated by Django 4.2.3 on 2025-10-18 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shorturl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={},
        ),
        migrations.AlterModelOptions(
            name="namespace",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="shorturl",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="shorturl",
            name="shorturl_sh_created_d182a8_idx",
        ),
        migrations.RemoveIndex(
            model_name="shorturl",
            name="shorturl_sh_is_acti_190890_idx",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="description",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="shorturl",
            name="description",
        ),
        migrations.RemoveField(
            model_name="shorturl",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="shorturl",
            name="title",
        ),
        migrations.AlterField(
            model_name="membership",
            name="invited_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="shorturl.organization"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("editor", "Editor"), ("viewer", "Viewer")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="namespaces", to="shorturl.organization"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="namespace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shorturls", to="shorturl.namespace"
            ),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="original_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="shortcode",
            field=models.CharField(max_length=10),
        ),
    ]
